/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prog2.vista;

import java.io.IOException;
import static java.awt.Color.GREEN;
import static java.awt.Color.RED;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import prog2.Adaptador.Adaptador;

/**
 *
 * @author Aliciaa
 */
public class AppCentralUB extends javax.swing.JFrame{

    /**
     * Creates new form Prova
     */
    public AppCentralUB() {
        initComponents();
        central = new Adaptador();
        
        // les variables estan abaix
        variableNormal = new VariableNormal(VAR_NORM_MEAN, VAR_NORM_STD, VAR_NORM_SEED);
        demandaPotencia = generaDemandaPotencia();
        sldBarresControl.setValue(100);
        etDiaDemandaGuanys.setText("Dia: " + central.getDia() + " ,Guanys: " + central.getGuanys() + " , Demanda: " + this.demandaPotencia);
    }
    
    private float generaDemandaPotencia(){
        float valor = Math.round(variableNormal.seguentValor());
        if (valor > DEMANDA_MAX)
            return DEMANDA_MAX;
        else
            if (valor < DEMANDA_MIN)
                return DEMANDA_MIN;
            else
                return valor;
    }
    
    private void finalitzaDia() {
        // Finalitzar dia
        this.textFiDia = central.finalitzaDia(demandaPotencia);
        
        // Generar i mostrar nova demanda de potencia
        demandaPotencia = generaDemandaPotencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrmGestioComponents = new javax.swing.JFrame();
        PnlGestioComponents = new javax.swing.JPanel();
        etBarresControl = new javax.swing.JLabel();
        sldBarresControl = new javax.swing.JSlider();
        txtIntroduirBarresControl = new javax.swing.JTextField();
        btnintroduirBarresControl = new javax.swing.JButton();
        btnAplicarModificacions = new javax.swing.JButton();
        btnCancelarModificacions = new javax.swing.JButton();
        etValorBarres = new javax.swing.JLabel();
        etReactor = new javax.swing.JLabel();
        pnlDesactivar = new javax.swing.JPanel();
        chkDesactivar = new javax.swing.JCheckBox();
        etBombes = new javax.swing.JLabel();
        pnlBomba1 = new javax.swing.JPanel();
        chkBomba1 = new javax.swing.JCheckBox();
        pnlBomba2 = new javax.swing.JPanel();
        chkBomba2 = new javax.swing.JCheckBox();
        pnlBomba3 = new javax.swing.JPanel();
        chkBomba3 = new javax.swing.JCheckBox();
        pnlBomba4 = new javax.swing.JPanel();
        chkBomba4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        pnlError = new javax.swing.JOptionPane();
        FrmVisualitzarInformacio = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        cmboxOpcionsVisualitzar = new javax.swing.JComboBox<>();
        btnMostrar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        digInformacio = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        etInformacio = new javax.swing.JTextArea();
        filechooserGC = new javax.swing.JFileChooser();
        pnlMenu = new javax.swing.JPanel();
        jbtnInfo = new javax.swing.JButton();
        jbtnComp = new javax.swing.JButton();
        jbtnFi = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCarregar = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        etDiaDemandaGuanys = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaFinalDia = new javax.swing.JTextArea();

        FrmGestioComponents.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FrmGestioComponentsWindowClosing(evt);
            }
        });

        etBarresControl.setText("Barres de Control");
        etBarresControl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sldBarresControl.setMajorTickSpacing(10);
        sldBarresControl.setOrientation(javax.swing.JSlider.VERTICAL);
        sldBarresControl.setPaintLabels(true);
        sldBarresControl.setPaintTicks(true);
        sldBarresControl.setValue(100);
        sldBarresControl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldBarresControl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldBarresControlStateChanged(evt);
            }
        });

        txtIntroduirBarresControl.setToolTipText("Introdueix el percentatge a inserir a les barres");
        txtIntroduirBarresControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntroduirBarresControlActionPerformed(evt);
            }
        });

        btnintroduirBarresControl.setText("Insereix");
        btnintroduirBarresControl.setToolTipText("Aplica els canvis a les barres");
        btnintroduirBarresControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnintroduirBarresControlActionPerformed(evt);
            }
        });

        btnAplicarModificacions.setText("Aplicar");
        btnAplicarModificacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarModificacionsActionPerformed(evt);
            }
        });

        btnCancelarModificacions.setText("Cancelar");
        btnCancelarModificacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificacionsActionPerformed(evt);
            }
        });

        etValorBarres.setText("Percentatge actual");
        etValorBarres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        etReactor.setText("Reactor");
        etReactor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlDesactivar.setBackground(new java.awt.Color(255, 51, 51));
        pnlDesactivar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkDesactivar.setText("Activar");
        chkDesactivar.setToolTipText("Vermell: desactivat\nVerd: activat\n");
        chkDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDesactivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDesactivarLayout = new javax.swing.GroupLayout(pnlDesactivar);
        pnlDesactivar.setLayout(pnlDesactivarLayout);
        pnlDesactivarLayout.setHorizontalGroup(
            pnlDesactivarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkDesactivar, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        pnlDesactivarLayout.setVerticalGroup(
            pnlDesactivarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkDesactivar, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        etBombes.setText("Bombes Refrigerants");
        etBombes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlBomba1.setBackground(new java.awt.Color(0, 255, 0));
        pnlBomba1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chkBomba1.setText("Bomba 1");
        chkBomba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBomba1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBomba1Layout = new javax.swing.GroupLayout(pnlBomba1);
        pnlBomba1.setLayout(pnlBomba1Layout);
        pnlBomba1Layout.setHorizontalGroup(
            pnlBomba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkBomba1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBomba1Layout.setVerticalGroup(
            pnlBomba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBomba1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(chkBomba1))
        );

        pnlBomba2.setBackground(new java.awt.Color(0, 255, 0));
        pnlBomba2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chkBomba2.setText("Bomba 2");
        chkBomba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBomba2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBomba2Layout = new javax.swing.GroupLayout(pnlBomba2);
        pnlBomba2.setLayout(pnlBomba2Layout);
        pnlBomba2Layout.setHorizontalGroup(
            pnlBomba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkBomba2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBomba2Layout.setVerticalGroup(
            pnlBomba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkBomba2)
        );

        pnlBomba3.setBackground(new java.awt.Color(0, 255, 0));
        pnlBomba3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chkBomba3.setText("Bomba 3");
        chkBomba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBomba3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBomba3Layout = new javax.swing.GroupLayout(pnlBomba3);
        pnlBomba3.setLayout(pnlBomba3Layout);
        pnlBomba3Layout.setHorizontalGroup(
            pnlBomba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkBomba3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBomba3Layout.setVerticalGroup(
            pnlBomba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkBomba3)
        );

        pnlBomba4.setBackground(new java.awt.Color(0, 255, 0));
        pnlBomba4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chkBomba4.setText("Bomba 4");
        chkBomba4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBomba4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBomba4Layout = new javax.swing.GroupLayout(pnlBomba4);
        pnlBomba4.setLayout(pnlBomba4Layout);
        pnlBomba4Layout.setHorizontalGroup(
            pnlBomba4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chkBomba4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
        );
        pnlBomba4Layout.setVerticalGroup(
            pnlBomba4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBomba4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(chkBomba4))
        );

        jLabel2.setText("Fora de Servei");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout PnlGestioComponentsLayout = new javax.swing.GroupLayout(PnlGestioComponents);
        PnlGestioComponents.setLayout(PnlGestioComponentsLayout);
        PnlGestioComponentsLayout.setHorizontalGroup(
            PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnCancelarModificacions)
                        .addGap(18, 18, 18)
                        .addComponent(btnAplicarModificacions))
                    .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                        .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                                .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etBarresControl)
                                    .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                                        .addComponent(sldBarresControl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIntroduirBarresControl)
                                            .addComponent(btnintroduirBarresControl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlGestioComponentsLayout.createSequentialGroup()
                                .addComponent(etValorBarres)
                                .addGap(58, 58, 58)))
                        .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etReactor)
                            .addComponent(etBombes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBomba1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBomba2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBomba3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBomba4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(235, 235, 235))
        );
        PnlGestioComponentsLayout.setVerticalGroup(
            PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                        .addComponent(etReactor)
                        .addGap(9, 9, 9)
                        .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                                .addComponent(pnlDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(etBombes)
                                    .addComponent(jLabel2))
                                .addGap(13, 13, 13)
                                .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                                        .addComponent(pnlBomba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(pnlBomba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(pnlBomba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(pnlBomba4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                                .addComponent(txtIntroduirBarresControl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnintroduirBarresControl)
                                .addGap(70, 70, 70)
                                .addComponent(etValorBarres))))
                    .addGroup(PnlGestioComponentsLayout.createSequentialGroup()
                        .addComponent(etBarresControl)
                        .addGap(18, 18, 18)
                        .addComponent(sldBarresControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(PnlGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAplicarModificacions)
                    .addComponent(btnCancelarModificacions))
                .addContainerGap())
        );

        txtIntroduirBarresControl.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout FrmGestioComponentsLayout = new javax.swing.GroupLayout(FrmGestioComponents.getContentPane());
        FrmGestioComponents.getContentPane().setLayout(FrmGestioComponentsLayout);
        FrmGestioComponentsLayout.setHorizontalGroup(
            FrmGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmGestioComponentsLayout.createSequentialGroup()
                .addComponent(PnlGestioComponents, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        FrmGestioComponentsLayout.setVerticalGroup(
            FrmGestioComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlGestioComponents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FrmVisualitzarInformacio.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                FrmVisualitzarInformacioWindowClosing(evt);
            }
        });

        jLabel1.setText("INFORMACIÓ CENTRAL");

        cmboxOpcionsVisualitzar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Opcio", "Mostrar Estat", "Mostrar quadern Bitàcola", "Mostrar Incidències" }));
        cmboxOpcionsVisualitzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxOpcionsVisualitzarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Acceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrmVisualitzarInformacioLayout = new javax.swing.GroupLayout(FrmVisualitzarInformacio.getContentPane());
        FrmVisualitzarInformacio.getContentPane().setLayout(FrmVisualitzarInformacioLayout);
        FrmVisualitzarInformacioLayout.setHorizontalGroup(
            FrmVisualitzarInformacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmVisualitzarInformacioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(FrmVisualitzarInformacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMostrar)
                    .addGroup(FrmVisualitzarInformacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmboxOpcionsVisualitzar, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrmVisualitzarInformacioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );
        FrmVisualitzarInformacioLayout.setVerticalGroup(
            FrmVisualitzarInformacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmVisualitzarInformacioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmboxOpcionsVisualitzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addGap(50, 50, 50)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        etInformacio.setColumns(20);
        etInformacio.setRows(5);
        jScrollPane2.setViewportView(etInformacio);

        javax.swing.GroupLayout digInformacioLayout = new javax.swing.GroupLayout(digInformacio.getContentPane());
        digInformacio.getContentPane().setLayout(digInformacioLayout);
        digInformacioLayout.setHorizontalGroup(
            digInformacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        digInformacioLayout.setVerticalGroup(
            digInformacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        filechooserGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filechooserGCActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AppCentralUB");

        jbtnInfo.setText("Informació Central");
        jbtnInfo.setToolTipText("Mostra l'informació de la central");
        jbtnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInfoActionPerformed(evt);
            }
        });

        jbtnComp.setText("Gestió Components");
        jbtnComp.setToolTipText("Gestiona els components de la central");
        jbtnComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCompActionPerformed(evt);
            }
        });

        jbtnFi.setText("Finalitzar Dia");
        jbtnFi.setToolTipText("Finalització del dia");
        jbtnFi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar ");
        btnGuardar.setToolTipText("Guarda les dades de la central");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCarregar.setText("Carregar");
        btnCarregar.setToolTipText("Carregar fitxer");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnFi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnFi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCarregar)
                .addGap(32, 32, 32))
        );

        lblTitle.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        lblTitle.setText("BENVINGUTS A LA CENTRAL UB");

        etDiaDemandaGuanys.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        etDiaDemandaGuanys.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prog2/vista/centralNuclear.png"))); // NOI18N
        jLabel3.setToolTipText("Representació de la nostra central");

        jTextAreaFinalDia.setColumns(20);
        jTextAreaFinalDia.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jTextAreaFinalDia.setRows(5);
        jScrollPane3.setViewportView(jTextAreaFinalDia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etDiaDemandaGuanys, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etDiaDemandaGuanys, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInfoActionPerformed
        FrmVisualitzarInformacio.setSize(400,400);
        FrmVisualitzarInformacio.setVisible(true);
        FrmVisualitzarInformacio.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_jbtnInfoActionPerformed

    private void jbtnCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCompActionPerformed
        FrmGestioComponents.setSize(500,400);
        FrmGestioComponents.setVisible(true);
        FrmGestioComponents.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        etValorBarres.setText("Valor actual: " + sldBarresControl.getValue());
        // serveix per a guardar les dades per si es dona al botó cancelar
        repositori();
        
        actualitzaBombes();
        actualitzaReactor();
        actualitzaBarres();
        
        llenar();
    }//GEN-LAST:event_jbtnCompActionPerformed

    private void jbtnFiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiActionPerformed
        finalitzaDia();
        etDiaDemandaGuanys.setText("Dia: " + central.getDia() + " , Guanys: " + central.getGuanys() + " , Demanda: " + this.demandaPotencia);
        jTextAreaFinalDia.setText(textFiDia);
    }//GEN-LAST:event_jbtnFiActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int seleccio = filechooserGC.showSaveDialog(this);
        if(seleccio == filechooserGC.APPROVE_OPTION){
            try{
                central.guardar(filechooserGC.getSelectedFile().getAbsolutePath());
                JOptionPane.showMessageDialog(pnlMenu, "Dades guardades correctament", "Guardat amb èxit", JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException | CentralUBException e){
               JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmboxOpcionsVisualitzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxOpcionsVisualitzarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboxOpcionsVisualitzarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        boolean trobat = true;
        switch (cmboxOpcionsVisualitzar.getSelectedIndex()) {
        //Estado
            case 1:
                etInformacio.setText(central.mostratEstat(demandaPotencia));
                break;
        //Bitacola
            case 2:
                etInformacio.setText(central.mostraBitacola());
                break;
        //Incidencias
            case 3:
                etInformacio.setText(central.getLlistaIncidencies());
                break;
            default:
                trobat = false;
                break;
        }
        if (trobat){
            etInformacio.setEditable(false);
            digInformacio.setSize(400,300);
            digInformacio.setVisible(true);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        cmboxOpcionsVisualitzar.setSelectedIndex(0);
        FrmVisualitzarInformacio.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void filechooserGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filechooserGCActionPerformed

    }//GEN-LAST:event_filechooserGCActionPerformed

    private void chkBomba4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBomba4ActionPerformed
        // TODO add your handling code here:
        try{
            if (chkBomba4.isSelected()){ 
                central.activaBomba(3);
            }
            else{
                central.desactivaBomba(3);
            }
        }catch(CentralUBException e){
            chkBomba4.setSelected(false);
            JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_chkBomba4ActionPerformed

    private void chkBomba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBomba1ActionPerformed
        try{
            if (chkBomba1.isSelected()) central.activaBomba(0);
            else central.desactivaBomba(0);
        }catch(CentralUBException e){
            chkBomba1.setSelected(false);
            JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_chkBomba1ActionPerformed

    private void chkDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDesactivarActionPerformed
        try{
            if(chkDesactivar.isSelected()){
                central.activaReactor();
                pnlDesactivar.setBackground(GREEN);
            }else{
                central.desactivaReactor();
                pnlDesactivar.setBackground(RED);
            }
        }catch(CentralUBException e){
            pnlDesactivar.setBackground(RED);
            chkDesactivar.setSelected(false);
            central.desactivaReactor();
            JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_chkDesactivarActionPerformed

    private void btnCancelarModificacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificacionsActionPerformed
        sldBarresControl.setValue(valorsld);
        
        if(select){
            chkDesactivar.setSelected(true);
//            pnlDesactivar.setBackground(GREEN);
            try{
                central.activaReactor();
            }catch(CentralUBException e){
                JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            chkDesactivar.setSelected(false);
//            pnlDesactivar.setBackground(RED);
            central.desactivaReactor();
        }
        
        if(bomba1){
            chkBomba1.setSelected(true);
            try{
                central.activaBomba(0);
            }catch(CentralUBException e){
                JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            chkBomba1.setSelected(false);
            central.desactivaBomba(0);
        }if(bomba2){
            chkBomba2.setSelected(true);
            try{
                central.activaBomba(1);
            }catch(CentralUBException e){
                JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            chkBomba2.setSelected(false);
            central.desactivaBomba(1);
        }if(bomba3){
            chkBomba3.setSelected(true);
            try{
                central.activaBomba(2);
            }catch(CentralUBException e){
                JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            chkBomba3.setSelected(false);
            central.desactivaBomba(2);
        }
        if(bomba4){
            chkBomba4.setSelected(true);
            try{
                central.activaBomba(3);
            }catch(CentralUBException e){
                JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            chkBomba4.setSelected(false);
            central.desactivaBomba(3);
        }
        txtIntroduirBarresControl.setText(String.valueOf(valorsld));
        FrmGestioComponents.setVisible(false);
    }//GEN-LAST:event_btnCancelarModificacionsActionPerformed

    private void btnAplicarModificacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarModificacionsActionPerformed
        try{
            if(txtIntroduirBarresControl.getText().equals("")){
                central.setInsercioBarres(sldBarresControl.getValue());
            }
            else if(sldBarresControl.getValue() != Integer.parseInt(txtIntroduirBarresControl.getText())){
                central.setInsercioBarres(sldBarresControl.getValue());
            }else{
                central.setInsercioBarres(sldBarresControl.getValue());
            }
            FrmGestioComponents.setVisible(false);
        }catch (CentralUBException e){
            JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAplicarModificacionsActionPerformed

    private void btnintroduirBarresControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnintroduirBarresControlActionPerformed
        sldBarresControl.setValue(Integer.parseInt(txtIntroduirBarresControl.getText()));
    }//GEN-LAST:event_btnintroduirBarresControlActionPerformed

    private void txtIntroduirBarresControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntroduirBarresControlActionPerformed
        sldBarresControl.setValue(Integer.parseInt(txtIntroduirBarresControl.getText()));
    }//GEN-LAST:event_txtIntroduirBarresControlActionPerformed

    private void sldBarresControlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldBarresControlStateChanged
        etValorBarres.setText("Valor actual: " + sldBarresControl.getValue());
        txtIntroduirBarresControl.setText(String.valueOf(sldBarresControl.getValue()));
    }//GEN-LAST:event_sldBarresControlStateChanged

    private void chkBomba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBomba2ActionPerformed
        // TODO add your handling code here:
        try{
            if (chkBomba2.isSelected()) central.activaBomba(1);
            else central.desactivaBomba(1);
        }catch(CentralUBException e){
            chkBomba2.setSelected(false);
            JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_chkBomba2ActionPerformed

    private void chkBomba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBomba3ActionPerformed
        // TODO add your handling code here:
        try{
            if (chkBomba3.isSelected()) central.activaBomba(2);
            else central.desactivaBomba(2);
        }catch(CentralUBException e){
            chkBomba3.setSelected(false);
            JOptionPane.showMessageDialog(PnlGestioComponents, e.getMessage(), "Error al aplicar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_chkBomba3ActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        // TODO add your handling code here:

        int seleccio = filechooserGC.showOpenDialog(this);
        if(seleccio == filechooserGC.APPROVE_OPTION){
            try{
                central.carregar(filechooserGC.getSelectedFile().getAbsolutePath());
                
                // actualitzar la seed
                int dia = central.getDia();
                this.variableNormal = new VariableNormal(VAR_NORM_MEAN, VAR_NORM_STD, VAR_NORM_SEED);
                for (int i = 0; i < dia; i++){
                    
                    demandaPotencia = generaDemandaPotencia();
                }
                etDiaDemandaGuanys.setText("Dia: " + dia + " , Guanys: " + central.getGuanys() + " , Demanda: " + demandaPotencia);
                JOptionPane.showMessageDialog(pnlMenu, "Dades carregades correctament", "Carregat amb èxit", JOptionPane.INFORMATION_MESSAGE);
            
            }catch(IOException | CentralUBException e){
                JOptionPane.showMessageDialog(pnlMenu, e.getMessage(), "Error al carregar", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void FrmGestioComponentsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FrmGestioComponentsWindowClosing
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(FrmGestioComponents, "Pressioni \"cancelar\" o bé \"Aplicar\"", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_FrmGestioComponentsWindowClosing

    private void FrmVisualitzarInformacioWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_FrmVisualitzarInformacioWindowClosing
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(FrmVisualitzarInformacio, "Pressioni \"Acceptar\" per sortir de la finestra", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_FrmVisualitzarInformacioWindowClosing
    
    void llenar(){
        DefaultListModel lista = new DefaultListModel();
        lista.clear();
        if(central.getForaServei(0)){
            lista.addElement("Bomba 1");
        }
        if(central.getForaServei(1)){
            lista.addElement("Bomba 2");
        }
        if(central.getForaServei(2)){
            lista.addElement("Bomba 3");
        }
        if(central.getForaServei(3)){
            lista.addElement("Bomba 4");
        }
        jList1.setModel(lista);
    }
    
    public void repositori(){
        valorsld = sldBarresControl.getValue();
        select = chkDesactivar.isSelected();
        bomba1 = chkBomba1.isSelected();
        bomba2 = chkBomba2.isSelected();
        bomba3 = chkBomba3.isSelected();
        bomba4 = chkBomba4.isSelected();
//        if(central.getActivatReactor()){
//            select = true;
//        }
//        if(chkBomba1.isSelected()){
//            bomba1 = true;
//        }
//        if(chkBomba2.isSelected()){
//            bomba2 = true;
//        }
//        if(chkBomba3.isSelected()){
//            bomba3 = true;
//        }
//        if(chkBomba4.isSelected()){
//            bomba4 = true;
//        }
    }
    
    public void actualitzaBombes(){

        chkBomba1.setSelected(central.getActivatBomba(0));
        chkBomba2.setSelected(central.getActivatBomba(1));
        chkBomba3.setSelected(central.getActivatBomba(2));
        chkBomba4.setSelected(central.getActivatBomba(3));
        
        pnlBomba1.setBackground(!central.getForaServei(0)?GREEN:RED);
        pnlBomba2.setBackground(!central.getForaServei(1)?GREEN:RED);
        pnlBomba3.setBackground(!central.getForaServei(2)?GREEN:RED);
        pnlBomba4.setBackground(!central.getForaServei(3)?GREEN:RED);
    }
    
    public void actualitzaReactor(){
        if (central.getActivatReactor()){
            pnlDesactivar.setBackground(GREEN);
            chkDesactivar.setSelected(true);
        }
        else {
            pnlDesactivar.setBackground(RED);
            chkDesactivar.setSelected(false);
        }
    }
    
    public void actualitzaBarres(){
        sldBarresControl.setValue((int)central.getInsercioBarres());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCentralUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCentralUB().setVisible(true);
            }
        });
    }
    
    Adaptador central;
    int valorsld;
    boolean select, bomba1, bomba2, bomba3, bomba4;
    String textFiDia;
    
    public final static float DEMANDA_MAX = 1600;
    public final static float DEMANDA_MIN = 200;
    public final static float VAR_NORM_MEAN = 1000;
    public final static float VAR_NORM_STD = 600;
    public final static long VAR_NORM_SEED = 123;
    
    /** Generador aleatori de la demanda de potència **/
    private VariableNormal variableNormal;
    
    /** Demanda de potència del dia actual **/
    private float demandaPotencia;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrmGestioComponents;
    private javax.swing.JFrame FrmVisualitzarInformacio;
    private javax.swing.JPanel PnlGestioComponents;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAplicarModificacions;
    private javax.swing.JButton btnCancelarModificacions;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnintroduirBarresControl;
    private javax.swing.JCheckBox chkBomba1;
    private javax.swing.JCheckBox chkBomba2;
    private javax.swing.JCheckBox chkBomba3;
    private javax.swing.JCheckBox chkBomba4;
    private javax.swing.JCheckBox chkDesactivar;
    private javax.swing.JComboBox<String> cmboxOpcionsVisualitzar;
    private javax.swing.JDialog digInformacio;
    private javax.swing.JLabel etBarresControl;
    private javax.swing.JLabel etBombes;
    private javax.swing.JLabel etDiaDemandaGuanys;
    private javax.swing.JTextArea etInformacio;
    private javax.swing.JLabel etReactor;
    private javax.swing.JLabel etValorBarres;
    private javax.swing.JFileChooser filechooserGC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaFinalDia;
    private javax.swing.JButton jbtnComp;
    private javax.swing.JButton jbtnFi;
    private javax.swing.JButton jbtnInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBomba1;
    private javax.swing.JPanel pnlBomba2;
    private javax.swing.JPanel pnlBomba3;
    private javax.swing.JPanel pnlBomba4;
    private javax.swing.JPanel pnlDesactivar;
    private javax.swing.JOptionPane pnlError;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JSlider sldBarresControl;
    private javax.swing.JTextField txtIntroduirBarresControl;
    // End of variables declaration//GEN-END:variables
}
